/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.login.view;

import br.com.ifba.usuario.entity.Usuario;

/**
 *
 * @author victo
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMensagem = new javax.swing.JTextArea();
        lblImagem = new javax.swing.JLabel();
        lblNaoTemConta = new javax.swing.JLabel();
        lblCadastreSe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setText("AppBarber");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 106, -1, -1));

        lblLogin.setText("Login:");
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 137, 37, -1));

        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 162, 37, -1));

        txtLogin.addActionListener(this::txtLoginActionPerformed);
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 134, 134, -1));
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 159, 134, -1));

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(this::btnEntrarActionPerformed);
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 193, -1, -1));

        txtMensagem.setColumns(20);
        txtMensagem.setRows(5);
        jScrollPane1.setViewportView(txtMensagem);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 220, -1));

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/login/imagens/imagemlogin.png"))); // NOI18N
        lblImagem.setText("jLabel5");
        getContentPane().add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 19, 96, 81));

        lblNaoTemConta.setText("Não tem uma Conta?");
        getContentPane().add(lblNaoTemConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        lblCadastreSe.setForeground(new java.awt.Color(0, 51, 255));
        lblCadastreSe.setText("<html><u>Cadastre-se</u></html>");
        lblCadastreSe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCadastreSe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastreSeMouseClicked(evt);
            }
        });
        getContentPane().add(lblCadastreSe, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        Usuario usuario = new Usuario();
        
        usuario.login = txtLogin.getText();
        usuario.senha = new String(txtSenha.getPassword());
        
        txtMensagem.setText("Login digitado: " + usuario.login + "\nSenha digitada: " + usuario.senha);
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void lblCadastreSeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastreSeMouseClicked
        // TODO add your handling code here:
        //Ao clicar abre a tela de cadastro
        TelaCadastro telaCadastro = new TelaCadastro();
        telaCadastro.setVisible(true);
        //fecha a tela
        this.dispose(); 
    }//GEN-LAST:event_lblCadastreSeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCadastreSe;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNaoTemConta;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextArea txtMensagem;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
